/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as verifierSol from "./Verifier.sol";
export type { verifierSol };
import type * as zFaceSol from "./ZFace.sol";
export type { zFaceSol };
export type { ArrayVerifierEntry } from "./ArrayVerifierEntry";
